### ISSUE TITLE
Passing dependencies onwards to other resolvers

### ISSUE THREAD

**Issue by andreialecu** [arcanis/pnp-webpack-plugin#16]
The plugin seems to hijack the resolver pipeline of `enhanced-resolve` and not pass imports to other resolver plugins down the chain if it itself cannot resolve them.

This breaks things like `resolve.modules` options and probably also aliases: https://webpack.js.org/configuration/resolve/#resolvemodules

`resolve.modules` is a common way of creating a common root of files in projects, so that imports look cleaner and don't end up in a mess of relative `../../../` paths. :)

I was able to confirm that simply changing this line:

https://github.com/arcanis/pnp-webpack-plugin/blob/master/index.js#L97

to: 

```js
        if (resolveContext.missingDependencies)
          resolveContext.missingDependencies.add(requestContext.path);
        if (resolveContext.log) resolveContext.log(error);
        return callback();
```

Correctly lets webpack/enhanced-resolve resolve files scoped to `resolve.modules`.

The only drawback is that dependency errors become a little less detailed.

Before:
![unknown](https://user-images.githubusercontent.com/697707/73010470-28eed000-3e1b-11ea-9483-907b056e51e8.png)

After:
![unknown](https://user-images.githubusercontent.com/697707/73010533-4459db00-3e1b-11ea-9ff6-853b931949cd.png)

I'm not sure if there's any drawback to this - I couldn't notice anything in my brief testing -, but if it's only an error message issue, I think a fix for that should be possible without breaking core webpack functionality.

**Comment by andreialecu** [comment]
If error messages are the only problem with this, I think the plugin could collect all pnp related errors and print them out at the end of the build if webpack reports a build failure. This should be possible, there are webpack notifier plugins that show popups when builds fail, so I'm sure there's a hook available.

**Comment by arcanis** [comment]
To anyone coming here for the same issue let's start with the best fix: use the `link:` protocol to explicitly define in your package.json the entries that you want to load. More information available on the Yarn 2 migration guide: [here](https://next.yarnpkg.com/advanced/migration#dont-use-resolvealiasmodules-webpack-or-modulenamemapper-jest).

Honestly I don't have the much bandwidth right now to spend on this issue, so I don't have opinion either way (I just don't consider it very high priority because it has a documented alternative). I'd tend to think that things are fine as they are, except that [`@yarnpkg/check`](https://github.com/yarnpkg/berry/tree/master/packages/yarnpkg-check) should detect the problem and suggest the fix.

**Comment by andreialecu** [comment]
Hey @arcanis so I opened a PR for this for your consideration. Thought I'd put some work into it besides just talking about it. :)

I think `link:` is definitely great for `node` projects, but webpack's purpose is to allow transforming code and imports based on custom rules - it's a compilation pipeline after all. I think it should be still allowed to do its job of transforming imports without needing additional quirks from package installation tools. After all it's just a resolution of transforming imports of **internal** files, and I think PnP should mostly concern itself with external packages.

Just my two cents :)

**Comment by andreialecu** [comment]
From what I can tell, the tests I referenced in my previous post were failing prior to my PR.
