### ISSUE TITLE
Webpack 5 Error 

### ISSUE THREAD

**Issue by ScriptedAlchemy** [arcanis/pnp-webpack-plugin#22]
Next.js is using `pnp` and I'm in the middle up upgrading to Webpack 5, along with their project. 
I'm getting the following error. 
```  "errors": [
    {
      "moduleIdentifier": "/Users/zjackson/ramdisk/dev/next.js/node_modules/enhanced-resolve/lib/ResolverFactory.js",
      "moduleName": "../next.js/node_modules/enhanced-resolve/lib/ResolverFactory.js",
      "loc": "74:11-28",
      "message": "Module not found: Error: Can't resolve 'pnpapi' in '/Users/zjackson/ramdisk/dev/next.js/node_modules/enhanced-resolve/lib'"
    }
  ]
}
```
when running: 
```js
export function resolveRequest(req: string, issuer: string) {
  // The `resolve` package is prebuilt through ncc, which prevents
  // PnP from being able to inject itself into it. To circumvent
  // this, we simply use PnP directly when available.
  if (process.versions.pnp) {
    const { resolveRequest } = require(`pnpapi`)

    return resolveRequest(req, issuer, { considerBuiltins: false })
  } else {
    const basedir =
      issuer.endsWith(path.posix.sep) || issuer.endsWith(path.win32.sep)
        ? issuer
        : path.dirname(issuer)
    return resolve.sync(req, { basedir })
  }
}
```

**Comment by arcanis** [comment]
@ScriptedAlchemy do you have a repo I can try? Some notes:

- Webpack 5 has builtin PnP support - you shouldn't need `pnp-webpack-plugin` anymore (there are some fixes I need to backport regarding aliases, but generally speaking it should just work).

- `Can't resolve 'pnpapi'` probably means that the PnP runtime isn't loaded - although it's weird, since you seem to be gating it behind `process.versions.pnp` which is only true in a PnP runtime 🤔

**Comment by ScriptedAlchemy** [comment]
Just realized that its built in haha

**Comment by rumblefrog** [comment]
Hey, perhaps some mention of v5 built-in in the readme would avoid some confusion.
